name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version to bump (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npm version ${{ github.event.inputs.version_type }}

      - name: Push changes and new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin HEAD:main --follow-tags